### ISSUE TITLE
Investigate TF Data Pipelines

### ISSUE THREAD

**Issue by lcross-sandia** [sandialabs/PyRIID#15]
Investigate TF Data Pipelines that will utilize the StaticSynthesizer where the next batch's data is loaded on the current batch's run. 

https://www.tensorflow.org/guide/data_performance

Open questions:
- Can StaticSynthesizer provide the same results given a seed?
    - If not, a paradigm that loads from StaticSynthesizer and saves data on disk on the first epoch , then uses data on disk for subsequent epochs?

**Comment by lcross-sandia** [comment]
Should be closed with acceptance of https://github.com/sandialabs/PyRIID/pull/32

**Comment by tymorrow** [comment]
Marking this as resolved--you investigated and were successful. 
However, due to project priorities and other changes, more investment will be needed at a later time, at which point I'll make a new issue.
