### ISSUE TITLE
Review Poisson-Bayes TF Implementation

### ISSUE THREAD

**Issue by tymorrow** [sandialabs/PyRIID#3]
Adding an issue as a reminder to review the TF implementation of Poisson-Bayes and reconcile it with the old predict method.

Steps:

1. Verify TF implementation works
2. Review and fix saving/loading as necessary

**Comment by ajhandley** [comment]
Adding notes to this issue, as it appears related to the Poisson-Bayes review.
- The restructured `get_row_labels()` method resolved by the merge for #4 now appears to break the call to `get_predictions()` and `get_labels()` used in the `classifier_comparison.py` example with the Poisson-Bayes model.
-  The Poisson-Bayes model is not modifying `SampleSet.prediction_probas` columns based on a `target_level` - `target_level` is never set in the model initialization or `make_model()` function. 
- If a Poisson-Bayes model is not initialized with an optional `SampleSet` of seeds, it does not complete the remainder of the initialization of class variables before returning; this includes a call to `initialize_info()`, the base class method that stores information like `target_level` in a manner that can be written to/from .h5 models.
