### ISSUE TITLE
run_test.sh doesn't work

### ISSUE THREAD

**Issue by lcross-sandia** [sandialabs/PyRIID#9]
On ubuntu system.

Command:
conda create --name pyriid python=3.7
conda activate pyriid
git clone <this repo>
pip install .
./run_tests.sh

Output:
`./run_tests.sh: line 2: coverage: command not found`

**Comment by tymorrow** [comment]
Please checkout out `main` and try again using the installation instructions in the README for **development**.
Please reach out to me directly if you continue having issues.
